Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,19 +1,123 @@
-# Starter pipeline
-# Start with a minimal pipeline that you can customize to build and deploy your code.
-# Add steps that build, run tests, deploy, and more:
-# https://aka.ms/yaml
-
+# Starter pipeline to deploy to qa7
 trigger:
-- master
+ branches:
+   include:
+     - qa7
+
+pr: none
 
 pool:
-  vmImage: ubuntu-latest
+  name: mdlive-test
 
-steps:
-- script: echo Hello, world!
-  displayName: 'Run a one-line script'
+variables:
+  - group: mdlive-qa
 
-- script: |
-    echo Add other tasks to build, test, and deploy your project.
-    echo See https://aka.ms/yaml
-  displayName: 'Run a multi-line script'
+stages:
+- stage: 'getAppConfig'
+  displayName: 'getAppConfig'
+  jobs:
+  - job: "getAppConfig"
+    steps:
+
+    - task: CopyFiles@2
+      displayName: 'Copy the source file to Staging directory'
+      inputs:
+        SourceFolder: '$(System.DefaultWorkingDirectory)'
+        Contents: |
+          **/*
+          !**/db/migrate/.#*
+          !.git/**/*
+          !.gitignore
+          !**/spec/**
+        TargetFolder: '$(Build.ArtifactStagingDirectory)'
+        CleanTargetFolder: true
+
+    - task: ArchiveFiles@2
+      displayName: 'Archive Files'
+      inputs:
+        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
+        includeRootFolder: false
+        archiveType: 'zip'
+        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
+        replaceExistingArchive: true
+
+    - task: PublishBuildArtifacts@1
+      displayName: 'Publish the Zip file'
+      inputs:
+        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
+        ArtifactName: 'drop'
+        publishLocation: 'Container'
+        Parallel: true
+        ParallelCount: 8
+
+- stage: 'DeploytoQA7'
+  displayName: 'Deploy to qa7'
+  jobs:
+  - deployment : deploymentjob
+    displayName: deploymentjob
+    environment:
+     name: mdlive-qa
+     resourceType: VirtualMachine
+     resourceName: mdlqa7-vm
+    strategy:
+     runOnce:
+       deploy:
+         steps:
+          - task: Bash@3
+            displayName: "App-Install"
+            inputs:
+              targetType: 'inline'
+              script: |
+                #!/bin/bash
+                set -e
+                echo "Deploying to $HOSTNAME"
+                QA_ENV=`echo $HOSTNAME | cut -d'-' -f1`
+                REL_VER="$(Build.BuildId)"
+                ART_NAME="$(Build.BuildId).zip"
+                REL_DIR="/home/deployer/apps/mdlkit/releases/$REL_VER"
+                REL_TMP_DIR="/home/deployer/apps/mdlkit/releases/$REL_VER/tmp"
+                APP_DIR="/home/deployer/apps/mdlkit/current"
+                echo "RELEASE VERSION: $REL_VER"
+                echo "RELEASE DIRECTORY: $REL_DIR"
+                echo "APPLICATION DIRECTORY: $APP_DIR"
+                echo "ARTIFACT NAME: $ART_NAME"
+                echo "**********************************************************"
+                echo "*      Creating required Directories                     *"
+                echo "**********************************************************"
+                mkdir -p /home/deployer/apps/mdlkit/shared/log
+                mkdir -p /home/deployer/apps/mdlkit/shared/pids
+                mkdir -p /home/deployer/apps/mdlkit/shared/cache
+                echo "Creating new release Direcory $REL_DIR"
+                mkdir -p $REL_DIR
+                echo "Creating new release Direcory $REL_DIR/tmp"
+                mkdir -p $REL_TMP_DIR
+                cp "$(Pipeline.Workspace)/drop/$(Build.BuildId).zip" $REL_DIR
+                cd $REL_DIR
+                echo 'unziping the file'
+                unzip -o $ART_NAME
+                rm -f $ART_NAME
+
+          - task: Bash@3
+            displayName: "Yarn - Install"
+            inputs:
+              targetType: 'inline'
+              script: |
+                #!/bin/bash
+                set -e
+                REL_VER="$(Build.BuildId)"
+                ART_NAME="$(Build.BuildId).zip"
+                REL_DIR="/home/deployer/apps/mdlkit/releases/$REL_VER"
+                cd $REL_DIR
+                source /home/deployer/.profile
+                NPM_TOKEN=$(NPM_TOKEN) yarn install
+
+          - task: Bash@3
+            displayName: mdlnext App Restart
+            inputs:
+              targetType: 'inline'
+              script: |
+                #!/bin/bash
+                set -e
+                echo "sudo systemctl restart mdlkit"
+                sudo systemctl restart mdlkit
+              failOnStderr: true
